# -*- coding: utf-8 -*-
"""ML2021Spring - HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ga642381/ML2021-Spring/blob/main/HW01/HW01.ipynb

# **Homework 1: COVID-19 Cases Prediction (Regression)**

Author: Heng-Jui Chang

Slides: https://github.com/ga642381/ML2021-Spring/blob/main/HW01/HW01.pdf  
Videos (Mandarin): https://cool.ntu.edu.tw/courses/4793/modules/items/172854  
https://cool.ntu.edu.tw/courses/4793/modules/items/172853  
Video (English): https://cool.ntu.edu.tw/courses/4793/modules/items/176529


Objectives:
* Solve a regression problem with deep neural networks (DNN).
* Understand basic DNN training tips.
* Get familiar with PyTorch.

If any questions, please contact the TAs via TA hours, NTU COOL, or email.

# **Download Data**


If the Google drive links are dead, you can download data from [kaggle](https://www.kaggle.com/c/ml2021spring-hw1/data), and upload data manually to the workspace.
"""

tr_path = 'covid.train.csv'  # path to training data
tt_path = 'covid.test.csv'   # path to testing data

# !gdown --id '19CCyCgJrUxtvgZF53vnctJiOJ23T5mqF' --output covid.train.csv
# !gdown --id '1CE240jLm2npU-tdz81-oVKEF3T2yfT1O' --output covid.test.csv

"""# **Import Some Packages**"""

# PyTorch
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

# For data preprocess
import numpy as np
import csv
import os

# For plotting
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

myseed = 0  # set a random seed for reproducibility
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
np.random.seed(myseed)
torch.manual_seed(myseed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(myseed)

"""# **Some Utilities**

You do not need to modify this part.
"""


def get_device():
    ''' Get device (if GPU is available, use GPU) '''
    return 'cuda' if torch.cuda.is_available() else 'cpu'


def plot_learning_curve(loss_record, title=''):
    ''' Plot learning curve of your DNN (train & dev loss) '''
    total_steps = len(loss_record['train'])
    x_1 = range(total_steps)
    x_2 = x_1[::len(loss_record['train']) // len(loss_record['dev'])]
    figure(figsize=(6, 4))
    plt.plot(x_1, loss_record['train'], c='tab:red', label='train')
    plt.plot(x_2, loss_record['dev'], c='tab:cyan', label='dev')
    plt.ylim(0.0, 5.)
    plt.xlabel('Training steps')
    plt.ylabel('MSE loss')
    plt.title('Learning curve of {}'.format(title))
    plt.legend()
    plt.show()


def plot_pred(dv_set, model, device, lim=35., preds=None, targets=None):
    ''' Plot prediction of your DNN '''
    if preds is None or targets is None:
        model.eval()
        preds, targets = [], []
        for x, y in dv_set:
            x, y = x.to(device), y.to(device)
            with torch.no_grad():
                pred = model(x)
                preds.append(pred.detach().cpu())
                targets.append(y.detach().cpu())
        preds = torch.cat(preds, dim=0).numpy()
        targets = torch.cat(targets, dim=0).numpy()

    figure(figsize=(5, 5))
    plt.scatter(targets, preds, c='r', alpha=0.5)
    plt.plot([-0.2, lim], [-0.2, lim], c='b')
    plt.xlim(-0.2, lim)
    plt.ylim(-0.2, lim)
    plt.xlabel('ground truth value')
    plt.ylabel('predicted value')
    plt.title('Ground Truth v.s. Prediction')
    plt.show()

"""# **Preprocess**

We have three kinds of datasets:
* `train`: for training
* `dev`: for validation
* `test`: for testing (w/o target value)

## **Dataset**

The `COVID19Dataset` below does:
* read `.csv` files
* extract features
* split `covid.train.csv` into train/dev sets
* normalize features

Finishing `TODO` below might make you pass medium baseline.
"""

class COVID19Dataset(Dataset):
    ''' Dataset for loading and preprocessing the COVID19 dataset '''
    def __init__(self,
                 path,
                 mode='train',
                 target_only=False):
        self.mode = mode

        # Read data into numpy arrays
        with open(path, 'r') as fp:
            data = list(csv.reader(fp))
            data = np.array(data[1:])[:, 1:].astype(float)

        id = [40, 41, 42, 43, 46, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 64, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
              82, 88, 89, 90, 91, 92]

        # if not target_only:
        #     # feats = list(range(93))
        #     ls1 = list(range(40))
        #     ls2 = [42, 43, 44, 46, 47, 48, 49, 50, 55, 56, 57, 60, 61, 62, 64, 65, 66, 67, 68, 73, 74, 75, 78, 79, 80, 82, 83, 84, 85, 86, 91, 92]
        #     feats = ls1 + id
        # else:
        #     # TODO: Using 40 states & 2 tested_positive features (indices = 57 & 75)
        #     ls1 = list(range(40))
        #     ls10 = [42, 43, 44, 45, 46, 47, 48, 49, 50, 55, 56, 57, 60, 61, 62, 63, 64, 65, 66, 67, 68, 73, 74, 75, 78,
        #             79, 80, 81, 82, 83, 84, 85, 86, 91, 92]
        #     ls15 = [42, 43, 44, 46, 47, 48, 49, 50, 55, 56, 57, 60, 61, 62, 64, 65, 66, 67, 68, 73, 74, 75, 78, 79, 80,
        #             82, 83, 84, 85, 86, 91, 92]
        #     ls20 = [42, 43, 44, 46, 47, 48, 49, 50, 55, 56, 57, 60, 61, 62, 64, 65, 66, 67, 68, 73, 74, 75, 78, 79, 80,
        #             82, 83, 84, 85, 86, 91, 92]
        #     ls25 = [42, 43, 44, 48, 49, 55, 56, 57, 60, 61, 62, 66, 67, 73, 74, 75, 78, 79, 80, 84, 85, 91, 92]
        #     ls30 = [42, 43, 48, 49, 55, 57, 60, 61, 66, 67, 73, 75, 78, 79, 84, 85, 91]
        #     ls2 = ls25
        #     feats = ls1 + id
        #     pass

        list_state = list(range(40))
        both_20 = [40, 41, 42, 43, 47, 48, 49, 51, 55, 56, 57, 58, 59, 60, 61, 65, 66, 67, 69, 73, 74, 75, 76, 77, 78, 79, 83, 84, 85, 87, 91, 92]    #  32

        both_25 = [40, 41, 42, 43, 47, 49, 51, 55, 56, 57, 58, 59, 60, 61, 65, 67, 69, 73, 74, 75, 76, 77, 78, 79, 83, 85, 87, 91, 92]

        both_50 = [40, 41, 42, 43, 51, 57, 58, 59, 60, 61, 69, 75, 76, 77, 78, 79, 87, 92]

        both_70 = [40, 41, 42, 43, 57, 58, 59, 60, 61, 75, 76, 77, 78, 79]
        # both = [40, 42, 43, 57, 58, 60, 61, 75, 78, 79]

        both = [40, 41, 42, 43, 51, 56, 57, 58, 59, 60, 61, 69, 74, 75, 76, 77, 78, 79, 87, 92]

        feats = list_state + both_50

        if mode == 'test':
            # Testing data
            # data: 893 x 93 (40 states + day 1 (18) + day 2 (18) + day 3 (17))
            data = data[:, feats]
            self.data = torch.FloatTensor(data)
        else:
            # Training data (train/dev sets)
            # data: 2700 x 94 (40 states + day 1 (18) + day 2 (18) + day 3 (18))
            target = data[:, -1]
            data = data[:, feats]
            
            # Splitting training data into train & dev sets
            if mode == 'train':
                indices = [i for i in range(len(data)) if i % 10 != 0]
            elif mode == 'dev':
                indices = [i for i in range(len(data)) if i % 10 == 0]
            
            # Convert data into PyTorch tensors
            self.data = torch.FloatTensor(data[indices])
            self.target = torch.FloatTensor(target[indices])

        # Normalize features (you may remove this part to see what will happen)
        self.data[:, 40:] = \
            (self.data[:, 40:] - self.data[:, 40:].mean(dim=0, keepdim=True)) \
            / self.data[:, 40:].std(dim=0, keepdim=True)

        self.dim = self.data.shape[1]

        print('Finished reading the {} set of COVID19 Dataset ({} samples found, each dim = {})'
              .format(mode, len(self.data), self.dim))

    def __getitem__(self, index):
        # Returns one sample at a time
        if self.mode in ['train', 'dev']:
            # For training
            return self.data[index], self.target[index]
        else:
            # For testing (no target)
            return self.data[index]

    def __len__(self):
        # Returns the size of the dataset
        return len(self.data)

"""## **DataLoader**

A `DataLoader` loads data from a given `Dataset` into batches.

"""

def prep_dataloader(path, mode, batch_size, n_jobs=0, target_only=False):
    ''' Generates a dataset, then is put into a dataloader. '''
    dataset = COVID19Dataset(path, mode=mode, target_only=target_only)  # Construct dataset
    dataloader = DataLoader(
        dataset, batch_size,
        shuffle=(mode == 'train'), drop_last=False,
        num_workers=n_jobs, pin_memory=True)                            # Construct dataloader
    return dataloader

"""# **Deep Neural Network**

`NeuralNet` is an `nn.Module` designed for regression.
The DNN consists of 2 fully-connected layers with ReLU activation.
This module also included a function `cal_loss` for calculating loss.

"""

class NeuralNet(nn.Module):
    ''' A simple fully-connected deep neural network '''
    def __init__(self, input_dim):
        super(NeuralNet, self).__init__()

        # Define your neural network here
        # TODO: How to modify this model to achieve better performance?
        self.net = nn.Sequential(
            # nn.BatchNorm1d(input_dim),
            nn.Linear(input_dim, 256),
            nn.Linear(256, 128),
            nn.LeakyReLU(),
            nn.Linear(128, 64),
            nn.LeakyReLU(),
            nn.Linear(64, 32),
            nn.Linear(32, 32),
            nn.LeakyReLU(),
            nn.Linear(32, 1)
        )
        self.l1 = nn.Linear(input_dim, 256)
        self.l2 = nn.Linear(256, 256)
        self.l3 = nn.Linear(256, 128)
        self.l4 = nn.Linear(128, 64)
        
        self.bn1 = nn.BatchNorm1d(256)
        self.bn2 = nn.BatchNorm1d(256)
        self.bn3 = nn.BatchNorm1d(128)
        self.bn4 = nn.BatchNorm1d(64)
        
        self.ac = nn.ReLU()
        self.out = nn.Linear(128, 1)
        self.drop = nn.Dropout(0.5)
        # Mean squared error loss
        self.criterion = nn.MSELoss(reduction='mean')

    def forward(self, x):
        ''' Given input of size (batch_size x input_dim), compute output of the network '''
        x = self.l1(x)
        x = self.ac(x)
        x = self.bn1(x)
        x = self.drop(x)
        
        x = self.l2(x)
        x = self.ac(x)
        x = self.bn2(x)
        x = self.drop(x)
        
        x = self.l3(x)
        x = self.ac(x)
        x = self.bn3(x)
        x = self.drop(x)
        
        # x = self.l4(x)
        # x = self.ac(x)
        # x = self.bn4(x)
        # x = self.drop(x)
        
        y = self.out(x)
        return y.squeeze(1)
        # return self.net(x).squeeze(1)

    def cal_loss(self, pred, target, w_l1, w_l2, print_flag=False):
        ''' Calculate loss '''
        # TODO: you may implement L1/L2 regularization here
        loss1 = 0
        loss2 = 0
        # print('-------------------------------------------------')
        # for para in self.parameters():
        #         # loss += torch.sum(torch.pow(para, 2))
        #
        #     print(type(para), )
        #     # print(para)
        for name, para in self.named_parameters():
            # print(name, type(name), len(para))
            if name in ['weight']:
                loss1 += torch.sum(abs(para))
                loss2 += torch.sum(torch.pow(para, 2))
                # print('ok', loss)
        # print('--------------------------------------------------------------------------------------')
        loss = self.criterion(pred, target)
        if print_flag:
            print('criterion:  ',  type(loss1), loss)
            print('l1:      :  ', type(loss), loss1)
            print('l2:      :  ', type(loss), loss2)
        # return loss1 + 0.0001 * loss
        return loss + w_l1 * loss1 + w_l2 * loss2, loss
"""# **Train/Dev/Test**

## **Training**
"""

def train(tr_set, dv_set, model, config, device):
    ''' DNN training '''

    n_epochs = config['n_epochs']  # Maximum number of epochs

    # Setup optimizer
    # optimizer = getattr(torch.optim, config['optimizer'])(
    #     model.parameters(), **config['optim_hparas'])
    # optimizer = torch.optim.Adam(model.parameters(), lr=0.00001, betas=(0.9, 0.99), eps=1e-08)
    optimizer = torch.optim.SGD(model.parameters(), lr=0.00003, momentum=0.9)
    min_mse = 1000.
    loss_record = {'train': [], 'dev': []}      # for recording training loss
    early_stop_cnt = 0
    epoch = 0
    while epoch < n_epochs:
        print('------------------   ', epoch,  '  ------------------------')
        model.train()                           # set model to training mode
        for x, y in tr_set:                     # iterate through the dataloader
            optimizer.zero_grad()               # set gradient to zero
            x, y = x.to(device), y.to(device)   # move data to device (cpu/cuda)
            pred = model(x)                     # forward pass (compute output)
            all_loss, mse_loss = model.cal_loss(pred, y, w_l1=config['weight_decay_l1'], w_l2=config['weight_decay_l2'], print_flag=False)  # compute loss
            all_loss.backward()                 # compute gradient (backpropagation)
            optimizer.step()                    # update model with optimizer
            loss_record['train'].append(mse_loss.detach().cpu().item())

        # After each epoch, test your model on the validation (development) set.
        dev_mse = dev(dv_set, model, device)
        if dev_mse < min_mse:
            # Save model if your model improved
            min_mse = dev_mse
            print('Saving model (epoch = {:4d}, loss = {:.4f})'
                .format(epoch + 1, min_mse))
            torch.save(model.state_dict(), config['save_path'])  # Save model to specified path
            early_stop_cnt = 0
        else:
            early_stop_cnt += 1

        epoch += 1
        # loss_record['train'].append(dev_mse)
        loss_record['dev'].append(dev_mse)
        if early_stop_cnt > config['early_stop']:
            # Stop training if your model stops improving for "config['early_stop']" epochs.
            print("Early Breaking !")
            break

    print('Finished training after {} epochs'.format(epoch))
    return min_mse, loss_record

"""## **Validation**"""

def dev(dv_set, model, device):
    model.eval()                                # set model to evalutation mode
    total_loss = 0
    for x, y in dv_set:                         # iterate through the dataloader
        x, y = x.to(device), y.to(device)       # move data to device (cpu/cuda)
        with torch.no_grad():                   # disable gradient calculation
            pred = model(x)                     # forward pass (compute output)
            all_loss, mse_loss = model.cal_loss(pred, y, w_l1=0, w_l2=0, print_flag=False)  # compute loss
        total_loss += mse_loss.detach().cpu().item() * len(x)  # accumulate loss
    total_loss = total_loss / len(dv_set.dataset)              # compute averaged loss
    print('Loss:  ', total_loss)
    return total_loss

"""## **Testing**"""

def test(tt_set, model, device):
    model.eval()                                # set model to evalutation mode
    preds = []
    for x in tt_set:                            # iterate through the dataloader
        x = x.to(device)                        # move data to device (cpu/cuda)
        with torch.no_grad():                   # disable gradient calculation
            pred = model(x)                     # forward pass (compute output)
            preds.append(pred.detach().cpu())   # collect prediction
    preds = torch.cat(preds, dim=0).numpy()     # concatenate all predictions and convert to a numpy array
    print('--------------------Testing Ends--------------------')
    return preds

"""# **Setup Hyper-parameters**

`config` contains hyper-parameters for training and the path to save your model.
"""

device = get_device()                 # get the current available device ('cpu' or 'cuda')
os.makedirs('models', exist_ok=True)  # The trained model will be saved to ./models/
target_only = False                   # TODO: Using 40 states & 2 tested_positive features

# TODO: How to tune these hyper-parameters to improve your model's performance?
config = {
    'n_epochs': 2000,                # maximum number of epochs
    'batch_size': 64,                # mini-batch size for dataloader
    'optimizer': 'Adam',             # optimization algorithm (optimizer in torch.optim)
    'optim_hparas': {                # hyper-parameters for the optimizer (depends on which optimizer you are using)
        'lr': 0.0001,                # learning rate of SGD
        'momentum': 0.85,            # momentum for SGD
    },
    'early_stop': 300,               # early stopping epochs (the number epochs since your model's last improvement)
    'save_path': 'models/model.pth',  # your model will be saved here
    'weight_decay_l1': 0.00005,
    'weight_decay_l2': 0.001,
}

"""# **Load data and model**"""

tr_set = prep_dataloader(tr_path, 'train', config['batch_size'], target_only=target_only)
dv_set = prep_dataloader(tr_path, 'dev', config['batch_size'], target_only=target_only)
tt_set = prep_dataloader(tt_path, 'test', config['batch_size'], target_only=target_only)

model = NeuralNet(tr_set.dataset.dim).to(device)  # Construct model and move to device
ckpt = torch.load(config['save_path'], map_location='cuda')  # Load your best model
model.load_state_dict(ckpt)
"""# **Start Training!**"""

model_loss, model_loss_record = train(tr_set, dv_set, model, config, device)

plot_learning_curve(model_loss_record, title='deep model')

del model
model = NeuralNet(tr_set.dataset.dim).to(device)
ckpt = torch.load(config['save_path'], map_location='cpu')  # Load your best model
model.load_state_dict(ckpt)
plot_pred(dv_set, model, device)  # Show prediction on the validation set

"""# **Testing**
The predictions of your model on testing set will be stored at `pred.csv`.
"""

def save_pred(preds, file):
    ''' Save predictions to specified file '''
    print('Saving results to {}'.format(file))
    with open(file, 'w') as fp:
        writer = csv.writer(fp)
        writer.writerow(['id', 'tested_positive'])
        for i, p in enumerate(preds):
            writer.writerow([i, p])

preds = test(tt_set, model, device)  # predict COVID-19 cases with your model
save_pred(preds, 'pred.csv')         # save prediction file to pred.csv

"""# **Hints**

## **Simple Baseline**
* Run sample code

## **Medium Baseline**
* Feature selection: 40 states + 2 `tested_positive` (`TODO` in dataset)

## **Strong Baseline**
* Feature selection (what other features are useful?)
* DNN architecture (layers? dimension? activation function?)
* Training (mini-batch? optimizer? learning rate?)
* L2 regularization
* There are some mistakes in the sample code, can you find them?

# **Reference**
This code is completely written by Heng-Jui Chang @ NTUEE.  
Copying or reusing this code is required to specify the original author. 

E.g.  
Source: Heng-Jui Chang @ NTUEE (https://github.com/ga642381/ML2021-Spring/blob/main/HW01/HW01.ipynb)
"""